Repository morib-in/Morib-Server-v2, pull requests merged in 2024-09, with the labels that each got.

#54 Fix [#53] 컴파일 에러 해결
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java
  morib/src/test/java/org/morib/server/MoribApplicationTests.java
Labels: refactor, fix

#56 Refactor [#52] 할당된 api 예외처리
  morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchTabNameServiceImpl.java
  morib/src/main/java/org/morib/server/domain/category/application/DeleteCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java
  morib/src/main/java/org/morib/server/global/exception/InvalidURLException.java
  morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
Labels: feat, refactor

#55 Feat [#51] 할당한 api 관련 예외 처리 관련 구현 진행
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoService.java
  morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoServiceImpl.java
  morib/src/main/java/org/morib/server/domain/user/application/FetchUserServiceImpl.java
Labels: feat

#58 Feat [#57] 구글 소셜 로그인, Spring Security 전면 적용
  morib/build.gradle
  morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java
  morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java
  morib/src/main/java/org/morib/server/api/modalView/controller/CategoryController.java
  morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java
  morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java
  morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
  morib/src/main/java/org/morib/server/domain/user/application/FetchUserService.java
  morib/src/main/java/org/morib/server/domain/user/infra/User.java
  morib/src/main/java/org/morib/server/domain/user/infra/UserRepository.java
  morib/src/main/java/org/morib/server/domain/user/infra/type/Role.java
  morib/src/main/java/org/morib/server/global/common/BaseResponse.java
  morib/src/main/java/org/morib/server/global/common/Constants.java
  morib/src/main/java/org/morib/server/global/common/TokenResponseDto.java
  morib/src/main/java/org/morib/server/global/config/SecurityConfig.java
  morib/src/main/java/org/morib/server/global/config/WebSecurityConfig.java
  morib/src/main/java/org/morib/server/global/jwt/CustomJwtAuthenticationEntryPoint.java
  morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java
  morib/src/main/java/org/morib/server/global/jwt/JwtService.java
  morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
  morib/src/main/java/org/morib/server/global/oauth2/CustomOAuth2User.java
  morib/src/main/java/org/morib/server/global/oauth2/OAuthAttributes.java
  morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginFailureHandler.java
  morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
  morib/src/main/java/org/morib/server/global/oauth2/userinfo/GoogleOAuth2UserInfo.java
  morib/src/main/java/org/morib/server/global/oauth2/userinfo/OAuth2UserInfo.java
  morib/src/main/java/org/morib/server/global/userauth/CustomUserAuthentication.java
  morib/src/main/java/org/morib/server/global/userauth/CustomUserDetails.java
  morib/src/main/java/org/morib/server/global/userauth/PrincipalHandler.java
Labels: feat, refactor

#61 Refactor [#59] api 명세서에 적힌 잘못된 응답, 네이밍 수정 작업 진행
  morib/src/main/java/org/morib/server/api/modalView/dto/AllowedSiteByTaskResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/vo/TaskInfoInAllowedSite.java
  morib/src/main/java/org/morib/server/api/timerView/dto/TaskInTodoCardDto.java
Labels: refactor

#63 Refactor [#62] 카테고리 start, endDate 삭제로 인한 로직 수정
  morib/src/main/java/org/morib/server/api/homeView/dto/fetch/HomeViewResponseDto.java
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/api/homeView/vo/CategoryInfo.java
  morib/src/main/java/org/morib/server/api/homeView/vo/TaskInfo.java
  morib/src/main/java/org/morib/server/api/modalView/dto/CreateCategoryRequestDto.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/vo/AllowedSiteInfo.java
  morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/category/infra/Category.java
Labels: refactor
