Repository morib-in/Morib-Server-v2, pull requests merged in 2024-08, with the labels that each got.

#2 Feat [#1] 초기 세팅
  morib/.gitignore
  morib/build.gradle
  morib/gradle/wrapper/gradle-wrapper.jar
  morib/gradle/wrapper/gradle-wrapper.properties
  morib/gradlew
  morib/gradlew.bat
  morib/settings.gradle
  morib/src/main/java/org/morib/server/MoribApplication.java
  morib/src/main/java/org/morib/server/api/homeViewApi/controller/HomeViewController.java
  morib/src/main/java/org/morib/server/api/homeViewApi/dto/HomeViewRequest.java
  morib/src/main/java/org/morib/server/api/homeViewApi/dto/HomeViewResponse.java
  morib/src/main/java/org/morib/server/api/homeViewApi/service/FetchService.java
  morib/src/main/java/org/morib/server/api/homeViewApi/service/fetch/HomeViewFacade.java
  morib/src/main/java/org/morib/server/domain/category/Category.java
  morib/src/main/java/org/morib/server/domain/category/infra/CategoryEntity.java
  morib/src/main/java/org/morib/server/domain/category/infra/CategoryRepository.java
  morib/src/test/java/org/morib/serer/MoribApplicationTests.java
Labels: feat

#8 Feat [#5] 타이머 뷰 스켈레톤 코드 구성
  .gitignore
  morib/src/main/java/org/morib/server/annotation/Facade.java
  morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java
  morib/src/main/java/org/morib/server/api/timerView/dto/StopTimerRequestDto.java
  morib/src/main/java/org/morib/server/api/timerView/dto/TaskInTodoCardDto.java
  morib/src/main/java/org/morib/server/api/timerView/dto/TodoCardResponseDto.java
  morib/src/main/java/org/morib/server/api/timerView/service/TimerViewFacade.java
  morib/src/main/java/org/morib/server/api/timerView/service/fetch/todo/FetchTodoService.java
  morib/src/main/java/org/morib/server/api/timerView/service/fetch/todo/FetchTodoServiceImpl.java
  morib/src/main/java/org/morib/server/api/timerView/service/stop/timer/StopTimerService.java
  morib/src/main/java/org/morib/server/api/timerView/service/stop/timer/StopTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/mset/application/MsetGateway.java
  morib/src/main/java/org/morib/server/domain/mset/application/MsetGatewayImpl.java
  morib/src/main/java/org/morib/server/domain/mset/infra/Mset.java
  morib/src/main/java/org/morib/server/domain/mset/infra/MsetRepository.java
  morib/src/main/java/org/morib/server/domain/permission/application/PermissionGateway.java
  morib/src/main/java/org/morib/server/domain/permission/application/PermissionGatewayImpl.java
  morib/src/main/java/org/morib/server/domain/permission/infra/Permission.java
  morib/src/main/java/org/morib/server/domain/permission/infra/PermissionRepository.java
  morib/src/main/java/org/morib/server/domain/todo/application/TodoGateway.java
  morib/src/main/java/org/morib/server/domain/todo/application/TodoGatewayImpl.java
  morib/src/main/java/org/morib/server/domain/todo/infra/Todo.java
  morib/src/main/java/org/morib/server/domain/todo/infra/TodoRepository.java
  morib/src/main/java/org/morib/server/domain/user/application/UserGateway.java
  morib/src/main/java/org/morib/server/domain/user/application/UserGatewayImpl.java
  morib/src/main/java/org/morib/server/domain/user/infra/User.java
  morib/src/main/java/org/morib/server/domain/user/infra/UserRepository.java
Labels: feat, skltn

#11 Feat [#10] Entity, 관련 Enum 세팅완료, DB 변경에 따른 네이밍 변경
  morib/src/main/java/org/morib/server/domain/allowedSite/application/AllowedSiteGateway.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/AllowedSiteGatewayImpl.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSite.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSiteRepository.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/type/OwnerType.java
  morib/src/main/java/org/morib/server/domain/category/infra/Category.java
  morib/src/main/java/org/morib/server/domain/mset/infra/Mset.java
  morib/src/main/java/org/morib/server/domain/mset/infra/MsetRepository.java
  morib/src/main/java/org/morib/server/domain/permission/infra/Permission.java
  morib/src/main/java/org/morib/server/domain/permission/infra/PermissionRepository.java
  morib/src/main/java/org/morib/server/domain/relationship/application/RelationshipGateway.java
  morib/src/main/java/org/morib/server/domain/relationship/application/RelationshipGatewayImpl.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/RelationshipRepository.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/type/RelationLevel.java
  morib/src/main/java/org/morib/server/domain/task/infra/Task.java
  morib/src/main/java/org/morib/server/domain/timer/infra/Timer.java
  morib/src/main/java/org/morib/server/domain/todo/infra/Todo.java
  morib/src/main/java/org/morib/server/domain/user/infra/User.java
  morib/src/main/java/org/morib/server/domain/user/infra/type/Platform.java
Labels: feat, refactor

#16 Feat [#15] 타이머뷰 타이머 내 할 일 카드 리스트 조회
  morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java
  morib/src/main/java/org/morib/server/api/timerView/dto/TaskInTodoCardDto.java
  morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
  morib/src/main/java/org/morib/server/api/timerView/service/TimerViewFacade.java
  morib/src/main/java/org/morib/server/api/timerView/service/fetch/todo/FetchTodoService.java
  morib/src/main/java/org/morib/server/api/timerView/service/stop/timer/StopTimerService.java
  morib/src/main/java/org/morib/server/api/timerView/service/stop/timer/StopTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/TaskManager.java
  morib/src/main/java/org/morib/server/domain/task/application/ClassifyTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskService.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/application/ClassifyTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/application/TimerManager.java
  morib/src/main/java/org/morib/server/domain/timer/infra/Timer.java
  morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoService.java
  morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoServiceImpl.java
  morib/src/main/java/org/morib/server/domain/todo/application/TodoGateway.java
  morib/src/main/java/org/morib/server/domain/todo/application/TodoGatewayImpl.java
  morib/src/main/java/org/morib/server/domain/todo/application/TodoManager.java
  morib/src/main/java/org/morib/server/domain/todo/infra/Todo.java
  morib/src/main/java/org/morib/server/domain/todo/infra/TodoRepository.java
  morib/src/main/java/org/morib/server/domain/user/application/FetchUserService.java
  morib/src/main/java/org/morib/server/domain/user/application/FetchUserServiceImpl.java
  morib/src/main/java/org/morib/server/domain/user/application/UserGateway.java
  morib/src/main/java/org/morib/server/domain/user/application/UserGatewayImpl.java
  morib/src/main/java/org/morib/server/domain/user/application/UserManager.java
  morib/src/main/java/org/morib/server/domain/user/infra/User.java
Labels: feat

#20 Refactor [#18] todoGateway 제거를 위한 작업 진행 및 일부 공동작업 진행
  morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
  morib/src/main/java/org/morib/server/domain/timer/infra/Timer.java
  morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoServiceImpl.java
  morib/src/main/java/org/morib/server/domain/todo/application/TodoGateway.java
  morib/src/main/java/org/morib/server/domain/todo/application/TodoGatewayImpl.java
Labels: refactor

#22 Feat [#21] Api 응답 클래스, Auditing 구현
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSite.java
  morib/src/main/java/org/morib/server/domain/category/infra/Category.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java
  morib/src/main/java/org/morib/server/domain/task/infra/Task.java
  morib/src/main/java/org/morib/server/domain/timer/infra/Timer.java
  morib/src/main/java/org/morib/server/domain/todo/infra/Todo.java
  morib/src/main/java/org/morib/server/domain/user/infra/User.java
  morib/src/main/java/org/morib/server/global/common/ApiResponseUtil.java
  morib/src/main/java/org/morib/server/global/common/BaseResponse.java
  morib/src/main/java/org/morib/server/global/common/BaseTimeEntity.java
  morib/src/main/java/org/morib/server/global/config/JpaAuditingConfig.java
  morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
  morib/src/main/java/org/morib/server/global/message/SuccessMessage.java
Labels: feat, refactor

#26 Feat [#25] 카테고리 생성 구현
  morib/src/main/java/org/morib/server/api/modalView/controller/CategoryController.java
  morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java
  morib/src/main/java/org/morib/server/api/modalView/dto/CreateCategoryRequestDto.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/domain/allowedSite/AllowedSiteManager.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/CreateAllowedSiteService.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/CreateAllowedSiteServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSite.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSiteRepository.java
  morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/category/infra/Category.java
  morib/src/main/java/org/morib/server/domain/category/infra/CategoryRepository.java
Labels: feat

#27 Feat [#24] 할 일 추가 후 타이머 시작
  morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java
  morib/src/main/java/org/morib/server/api/homeView/dto/StartTimerRequestDto.java
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskService.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/todo/TodoManager.java
  morib/src/main/java/org/morib/server/domain/todo/application/CreateTodoService.java
  morib/src/main/java/org/morib/server/domain/todo/application/CreateTodoServiceImpl.java
  morib/src/main/java/org/morib/server/domain/todo/infra/Todo.java
Labels: feat

#29 Fix [#28] 잘못 사용된 어노테이션 수정 및 이전 잘못되었던 stopTimer 로직 변경 작업 진행
  morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java
  morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/infra/TimerRepository.java
Labels: refactor, fix

#31 Feat [#30] 태스크 생성 api 구현
  morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java
  morib/src/main/java/org/morib/server/api/homeView/dto/CreateTaskRequestDto.java
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/category/infra/CategoryRepository.java
  morib/src/main/java/org/morib/server/domain/task/application/CreateTaskService.java
  morib/src/main/java/org/morib/server/domain/task/application/CreateTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/infra/Task.java
Labels: feat

#35 Feat [#34] 오늘 나의 작업시간 조회 api 구현
  morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java
  morib/src/main/java/org/morib/server/api/homeView/dto/fetch/FetchMyElapsedTimeResponseDto.java
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/domain/task/infra/TaskRepository.java
  morib/src/main/java/org/morib/server/domain/timer/TimerManager.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/infra/TimerRepository.java
Labels: feat

#33 Feat [#32] 다른 카테고리에서 모립세트 불러오기
  morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java
  morib/src/main/java/org/morib/server/api/modalView/dto/AllowedSiteByCategoryResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/vo/AllowSiteForCalledByCatgory.java
  morib/src/main/java/org/morib/server/api/modalView/vo/CategoryInfoInAllowedSite.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteService.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSiteRepository.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/category/infra/CategoryRepository.java
Labels: feat

#40 Feat [#37] 특정 태스크의 모립세트 불러오기 api 작업
  morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java
  morib/src/main/java/org/morib/server/api/modalView/dto/AllowedSiteByCategoryResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/dto/AllowedSiteByTaskResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/vo/AllowSiteForCalledByTask.java
  morib/src/main/java/org/morib/server/api/modalView/vo/TaskInfoInAllowedSite.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteService.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/infra/TaskRepository.java
Labels: feat

#39 Feat [#38] 태스크 상태 변경 api 구현
  morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/domain/task/TaskManager.java
  morib/src/main/java/org/morib/server/domain/task/infra/Task.java
Labels: feat

#36 Refactor [#23] 홈뷰 전체 조회 리팩토링
  morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java
  morib/src/main/java/org/morib/server/api/homeView/dto/fetch/FetchCombinedDto.java
  morib/src/main/java/org/morib/server/api/homeView/dto/fetch/HomeViewResponseDto.java
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/api/homeView/vo/CategoriesByDate.java
  morib/src/main/java/org/morib/server/api/homeView/vo/CategoryInfo.java
  morib/src/main/java/org/morib/server/api/homeView/vo/CategoryWithTasks.java
  morib/src/main/java/org/morib/server/api/homeView/vo/CombinedByDate.java
  morib/src/main/java/org/morib/server/api/homeView/vo/CombinedCategoryAndTaskInfo.java
  morib/src/main/java/org/morib/server/api/homeView/vo/TaskInfo.java
  morib/src/main/java/org/morib/server/api/homeView/vo/TaskWithElapsedTime.java
  morib/src/main/java/org/morib/server/api/homeView/vo/TaskWithTimers.java
  morib/src/main/java/org/morib/server/api/homeView/vo/TasksByCategory.java
  morib/src/main/java/org/morib/server/domain/category/CategoryManager.java
  morib/src/main/java/org/morib/server/domain/category/application/ClassifyCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/ClassifyCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/TaskManager.java
  morib/src/main/java/org/morib/server/domain/task/application/ClassifyTaskService.java
  morib/src/main/java/org/morib/server/domain/task/application/ClassifyTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskService.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/application/ToggleTaskStatusService.java
  morib/src/main/java/org/morib/server/domain/task/application/ToggleTaskStatusServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/application/ClassifyTimerService.java
  morib/src/main/java/org/morib/server/domain/timer/application/ClassifyTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java
  morib/src/main/java/org/morib/server/global/common/DataUtils.java
Labels: refactor

#44 Feat [#41] 유저의 모든 카테고리 조회 api 구현
  morib/src/main/java/org/morib/server/api/modalView/controller/CategoryController.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
Labels: feat

#45 Feat [#42] 카테고리 삭제 api 구현
  morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/domain/category/application/DeleteCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/DeleteCategoryServiceImpl.java
Labels: feat

#48 Fix [#47] conflict 해결 중 빠진 부분 fix 및 추가적으로 발견된 리팩토링 작업 진행합니다.
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/application/CreateTaskService.java
  morib/src/main/java/org/morib/server/domain/task/application/CreateTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java
  morib/src/main/java/org/morib/server/domain/todo/application/CreateTodoService.java
  morib/src/main/java/org/morib/server/domain/todo/application/CreateTodoServiceImpl.java
  morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoService.java
  morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoServiceImpl.java
Labels: refactor, fix
