Repository morib-in/Morib-Server-v2, pull requests merged in 2024-12, with the labels that each got.

#74 Feat [#73] deleteTask api 구현 작업 진행
  morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/domain/task/application/DeleteTaskService.java
  morib/src/main/java/org/morib/server/domain/task/application/DeleteTaskServiceImpl.java
Labels: enhancement

#76 Feat [#72] 설정 관련 api 구현
  morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/api/settingView/controller/SettingViewController.java
  morib/src/main/java/org/morib/server/api/settingView/dto/FetchUserProfileResponseDto.java
  morib/src/main/java/org/morib/server/api/settingView/dto/UpdateUserProfileRequestDto.java
  morib/src/main/java/org/morib/server/api/settingView/facade/SettingViewFacade.java
  morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
  morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
  morib/src/main/java/org/morib/server/domain/user/UserManager.java
  morib/src/main/java/org/morib/server/domain/user/application/dto/UpdateUserProfileServiceDto.java
  morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserService.java
  morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserServiceImpl.java
  morib/src/main/java/org/morib/server/domain/user/infra/User.java
Labels: feat, refactor

#80 Feat [#79] 친구 목록 / 받은&보낸 요청 조회 api 구현
  morib/src/main/java/org/morib/server/api/modalView/controller/RelationshipController.java
  morib/src/main/java/org/morib/server/api/modalView/dto/FetchRelationshipResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/dto/FetchUnconnectedRelationshipResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipService.java
  morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/RelationshipRepository.java
Labels: feat

#84 Feat [#83] 허용서비스 세트 삭제 api 구현 allowServiceSet -> 내부에서는 allowGroup 으로 명명
  morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java
  morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/DeleteAllowedGroupService.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/impl/DeleteAllowedGroupServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/infra/AllowedGroupRepository.java
Labels: enhancement, feat

#88 [Feat] 허용 서비스 세트 정보 변경 (컬러 or 이름)
  morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/UpdateAllowedGroupColorCodeRequestDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/UpdateAllowedGroupNameRequestDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/AllowedGroupManager.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/impl/DeleteAllowedGroupServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/infra/AllowedGroup.java
  morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java
  morib/src/main/java/org/morib/server/global/exception/InvalidQueryParameterException.java
Labels: enhancement, feat

#95 Feat [#92] 친구 추가 요청 api 구현
  morib/build.gradle
  morib/src/main/java/org/morib/server/api/modalView/controller/RelationshipController.java
  morib/src/main/java/org/morib/server/api/modalView/dto/CreateRelationshipRequestDto.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/api/settingView/controller/SettingViewController.java
  morib/src/main/java/org/morib/server/domain/relationship/RelationshipManager.java
  morib/src/main/java/org/morib/server/domain/relationship/application/CreateRelationshipService.java
  morib/src/main/java/org/morib/server/domain/relationship/application/CreateRelationshipServiceImpl.java
  morib/src/main/java/org/morib/server/domain/relationship/application/DeleteRelationshipService.java
  morib/src/main/java/org/morib/server/domain/relationship/application/DeleteRelationshipServiceImpl.java
  morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipService.java
  morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java
  morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipService.java
  morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipServiceImpl.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java
  morib/src/main/java/org/morib/server/domain/relationship/infra/RelationshipRepository.java
  morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserService.java
  morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserServiceImpl.java
  morib/src/main/java/org/morib/server/domain/user/infra/UserRepository.java
  morib/src/main/java/org/morib/server/global/common/Constants.java
  morib/src/main/java/org/morib/server/global/exception/AlreadyFriendException.java
  morib/src/main/java/org/morib/server/global/exception/AlreadyFriendRequestException.java
  morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java
  morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
  morib/src/main/java/org/morib/server/global/sse/SseController.java
  morib/src/main/java/org/morib/server/global/sse/SseEmitters.java
Labels: feat
