Repository morib-in/Morib-Server-v2, pull requests merged in 2025-01, with the labels that each got.

#98 Feat [#91] 허용서비스세트 리스트조회, 상세조회 api 구현
  morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/AllowedSiteVo.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllAllowedGroupsResponseDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllowedGroupDetailResponseDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/FetchAllowedGroupService.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/impl/FetchAllowedGroupServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/infra/AllowedGroup.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/infra/AllowedGroupRepository.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSite.java
  morib/src/main/java/org/morib/server/global/common/ConnectType.java
Labels: feat

#103 Feat [#101] SSE 관련 친구 온/오프라인 트래킹 기능 구현
  morib/src/main/java/org/morib/server/api/modalView/dto/FetchRelationshipRequestsResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/dto/FetchRelationshipResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/dto/FetchUnconnectedRelationshipResponseDto.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java
  morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java
  morib/src/main/java/org/morib/server/global/exception/SSEConnectionException.java
  morib/src/main/java/org/morib/server/global/sse/SseController.java
  morib/src/main/java/org/morib/server/global/sse/SseEmitters.java
Labels: feat, refactor

#104 Feat [#102] 로그아웃, 회원탈퇴, 토큰 재발급 api 구현
  morib/.gitignore
  morib/src/main/java/org/morib/server/MoribApplication.java
  morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java
  morib/src/main/java/org/morib/server/api/loginView/dto/UserReissueRequestDto.java
  morib/src/main/java/org/morib/server/api/loginView/facade/UserAuthFacade.java
  morib/src/main/java/org/morib/server/domain/user/UserManager.java
  morib/src/main/java/org/morib/server/domain/user/application/dto/ReissueTokenServiceDto.java
  morib/src/main/java/org/morib/server/domain/user/application/service/DeleteUserService.java
  morib/src/main/java/org/morib/server/domain/user/application/service/DeleteUserServiceImpl.java
  morib/src/main/java/org/morib/server/domain/user/application/service/ReissueTokenService.java
  morib/src/main/java/org/morib/server/domain/user/application/service/ReissueTokenServiceImpl.java
  morib/src/main/java/org/morib/server/domain/user/infra/User.java
  morib/src/main/java/org/morib/server/global/common/Constants.java
  morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java
  morib/src/main/java/org/morib/server/global/config/SecurityConfig.java
  morib/src/main/java/org/morib/server/global/jwt/JwtService.java
  morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
  morib/src/main/java/org/morib/server/global/oauth2/CustomOAuth2User.java
  morib/src/main/java/org/morib/server/global/oauth2/handler/CustomLogoutHandler.java
  morib/src/main/java/org/morib/server/global/oauth2/handler/CustomLogoutSuccessHandler.java
  morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
Labels: feat

#112 Feat [#108] 커스텀 Validation 추가
  morib/src/main/java/org/morib/server/annotation/ValidUrl.java
  morib/src/main/java/org/morib/server/global/common/UrlValidator.java
  morib/src/main/java/org/morib/server/global/exception/DuplicateResourceException.java
  morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java
Labels: feat, refactor

#109 Refactor [#106] AllowedService 관련 네이밍 수정
  morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/AllowedSiteVo.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/CreateAllowedSiteRequestDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllAllowedGroupsResponseDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllowedGroupListResponseDto.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/dto/CreateAllowedSiteInAllowedGroupServiceDto.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/dto/CreateAllowedSiteServiceDto.java
  morib/src/main/java/org/morib/server/domain/user/infra/type/InterestAreaSiteVo.java
Labels: refactor

#111 Feat [#107] 허용 서비스 세트 추가, 온보딩 API 구현
  morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/CreateAllowedGroupResponse.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/CreateAllowedSiteInAllowedGroupRequestDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllowedGroupDetailResponseDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllowedGroupResponseDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/InterestAreaSiteResponseDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/UpdateAllowedGroupColorCodeRequestDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/dto/UpdateAllowedGroupNameRequestDto.java
  morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/CreateAllowedGroupService.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/FetchAllowedGroupService.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/impl/CreateAllowedGroupServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/application/impl/FetchAllowedGroupServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/infra/AllowedGroup.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/infra/AllowedGroupRepository.java
  morib/src/main/java/org/morib/server/domain/allowedGroup/infra/type/ColorCode.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/CreateAllowedSiteService.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/CreateAllowedSiteServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteService.java
  morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteServiceImpl.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSite.java
  morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSiteRepository.java
  morib/src/main/java/org/morib/server/domain/user/UserManager.java
  morib/src/main/java/org/morib/server/domain/user/infra/User.java
  morib/src/main/java/org/morib/server/domain/user/infra/type/InterestArea.java
  morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
Labels: feat, refactor

#114 Refactor [#113] SSE 관련 클래스 아키텍처 리팩토링
  morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java
  morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java
  morib/src/main/java/org/morib/server/api/timerView/dto/StopTimerRequestDto.java
  morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
  morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipService.java
  morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/application/CreateTimerService.java
  morib/src/main/java/org/morib/server/domain/timer/application/CreateTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java
  morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java
  morib/src/main/java/org/morib/server/domain/timer/infra/Timer.java
  morib/src/main/java/org/morib/server/domain/timer/infra/TimerRepository.java
  morib/src/main/java/org/morib/server/global/common/Constants.java
  morib/src/main/java/org/morib/server/global/common/HealthCheckController.java
  morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java
  morib/src/main/java/org/morib/server/global/message/SseMessageBuilder.java
  morib/src/main/java/org/morib/server/global/sse/api/SseController.java
  morib/src/main/java/org/morib/server/global/sse/api/SseEventHandler.java
  morib/src/main/java/org/morib/server/global/sse/api/SseFacade.java
  morib/src/main/java/org/morib/server/global/sse/api/UserInfoDtoForSseUserInfoWrapper.java
  morib/src/main/java/org/morib/server/global/sse/application/event/SseDisconnectEvent.java
  morib/src/main/java/org/morib/server/global/sse/application/event/SseTimeoutEvent.java
  morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java
  morib/src/main/java/org/morib/server/global/sse/application/repository/SseUserInfoWrapper.java
  morib/src/main/java/org/morib/server/global/sse/application/service/SseSender.java
  morib/src/main/java/org/morib/server/global/sse/application/service/SseService.java
Labels: refactor
